# Generated by Django 5.2.7 on 2025-10-22 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='sale_date',
        ),
        migrations.AddField(
            model_name='installmentpayment',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesapp.salesperson', verbose_name='المُحصّل المسؤول'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر الشراء'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='salesperson_commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نسبة عمولة المندوب (٪)'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='is_cash_sale',
            field=models.BooleanField(default=False, verbose_name='بيع كاش؟'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='sale_month',
            field=models.PositiveIntegerField(default=10, verbose_name='شهر البيع'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='sale_year',
            field=models.PositiveIntegerField(default=2025, verbose_name='سنة البيع'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='مدفوع؟'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='payment_date',
            field=models.DateField(verbose_name='تاريخ الدفعة المستحقة'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='salesapp.receipt', verbose_name='الوصل التابع له'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.branch', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='اسم العميل'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesapp.salesperson', verbose_name='المندوب (البائع)'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesapp.inventoryitem', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='salesapp.receipt', verbose_name='الوصل التابع له'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الموظف'),
        ),
    ]
