# Generated by Django 5.2.7 on 2025-10-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0002_remove_receipt_sale_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='salesperson_commission_rate',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='salesperson_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قيمة عمولة المندوب (مبلغ ثابت)'),
        ),
    ]
