# Generated by Django 5.2.7 on 2025-10-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0003_remove_inventoryitem_salesperson_commission_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentpayment',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='purchase_price',
            field=models.PositiveIntegerField(default=0, verbose_name='سعر الشراء'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='salesperson_commission_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='قيمة عمولة المندوب (مبلغ ثابت)'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='down_payment',
            field=models.PositiveIntegerField(default=0, verbose_name='المقدم'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='sale_month',
            field=models.PositiveIntegerField(verbose_name='شهر البيع'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='sale_year',
            field=models.PositiveIntegerField(verbose_name='سنة البيع'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.PositiveIntegerField(verbose_name='سعر الوحدة'),
        ),
    ]
