# Generated by Django 5.2.7 on 2025-10-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0004_alter_installmentpayment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='كود الفرع'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='product_code',
            field=models.CharField(default=1, max_length=50, verbose_name='كود المنتج'),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='code',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='كود الموظف'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم الفرع'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='payment_date',
            field=models.DateField(verbose_name='تاريخ الدفعة المستقة'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('name', 'branch'), ('product_code', 'branch')},
        ),
        migrations.AlterUniqueTogether(
            name='salesperson',
            unique_together={('name', 'branch')},
        ),
    ]
