# Generated by Django 5.2.7 on 2025-10-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0005_branch_code_inventoryitem_product_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='كود الفرع'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='product_code',
            field=models.CharField(max_length=50, verbose_name='كود المنتج'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='كود الموظف'),
        ),
    ]
