# Generated by Django 5.2.7 on 2025-10-22 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0006_alter_branch_code_alter_inventoryitem_product_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('name', 'branch')},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='code',
        ),
        migrations.RemoveField(
            model_name='salesperson',
            name='code',
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='salesapp.salesperson', verbose_name='المُحصّل المسؤول'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesapp.branch', verbose_name='مخزن الفرع'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesapp.branch', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='salesapp.salesperson', verbose_name='المندوب (البائع)'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesapp.branch', verbose_name='الفرع التابع له'),
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='product_code',
        ),
    ]
