# Generated by Django 5.2.7 on 2025-10-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0007_alter_inventoryitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='products_text',
            field=models.TextField(blank=True, null=True, verbose_name='نص المنتجات (للطباعة)'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.PositiveIntegerField(editable=False, unique=True, verbose_name='رقم الوصل'),
        ),
    ]
